### ISSUE TITLE
eventProxy() TypeError (Preact X)

### ISSUE THREAD

**Issue by qw-in** [developit/preact#1350]
Not sure if this is intended or not but while porting over legacy jQuery code to Preact X I ran into this cryptic error message:

```
preact.mjs?e1dc:1 Uncaught TypeError: this.n[n.type] is not a function
    at HTMLImageElement.k
```

I found out that it was caused by an old `onError` prop

```
<img onError="/* jquery stuff */" />
```

https://github.com/developit/preact/blob/cd6f005bceb4b34e33063b8f131d97a62bf55993/src/diff/props.js#L100-L102

Could probably do a more explicit type check here but not sure if it is worth the bytes. Happy to add a PR if desired

**Comment by marvinhagemeister** [comment]
This is a good candidate for our debug addon that lives in `preact/debug`. They are build to warn in case of bad properties and are only used during `development` in most setups.

**Comment by developit** [comment]
Might also be worth considering this suggestion from @uppercod:

https://twitter.com/Uppercod/status/1103336598178013186

**Comment by cristianbote** [comment]
Honestly, I really like @UpperCod's suggestion. Would make things really straight forward for event handling. Right?

**Comment by developit** [comment]
It would mean non-function values never get assigned as handlers. TBH the one drawback here is that it would prevent Preact from ever supporting DOM EventHandler interface:

```
class Foo {
  handleEvent(e) {
    // nicety: `this` is the component
    if (e.type == 'click') this.setState({ clicked: true });
  }
  render() {
    return <button onClick={this} />
  }
```

**Comment by marvinhagemeister** [comment]
Agree, this may lead us down a rabbit hole.
