### ISSUE TITLE
8.2.2 fails to install

### ISSUE THREAD

**Issue by cletusw** [developit/preact#834]
preact 8.2.2 fails to install with the error
```
npm ERR! Linux 3.13.0-128-generic
npm ERR! argv "<..."> "<..."> "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! preact@8.2.2 postinstall: `node ./config/donation-message.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the preact@8.2.2 postinstall script 'node ./config/donation-message.js'.
```

Works fine in 8.2.1

**Comment by cletusw** [comment]
@developit This was working fine in 8.2.1. Maybe related to #804 ?

**Comment by cletusw** [comment]
Also, if I just `npm i preact@8.2.2`:
```
> preact@8.2.2 postinstall <...>/node_modules/preact
> node ./config/donation-message.js

module.js:487
    throw err;
    ^

Error: Cannot find module '<...>/node_modules/preact/config/donation-message.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

Maybe npm doesn't create the preact folder until after the postinstall?

**Comment by lukeed** [comment]
This is the why: https://github.com/developit/preact/commit/4ea1bc7998e78f0ac33112133913a73abab4fe62##commitcomment-23850785

**Comment by developit** [comment]
Yup I totally blanked on it, just pushed a fix. 8.2.3!
